"""Render a stored scan (store.get_scan dict) into Markdown / HTML / PDF.

No hard template-engine dependency: HTML/Markdown are built with the stdlib so
they always work. PDF uses WeasyPrint if it's importable, otherwise raises a
clear error the API surfaces as 501.
"""
from __future__ import annotations

import html as _html
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from ..base import SEVERITY_ORDER, severity_rank

try:  # optional heavy dependency
    from weasyprint import HTML as _WeasyHTML  # type: ignore
    PDF_AVAILABLE = True
except Exception:  # noqa: BLE001
    PDF_AVAILABLE = False

SEV_COLORS = {
    "critical": "#b366ff",
    "high": "#ff5b6a",
    "medium": "#ffb020",
    "low": "#38bdf8",
    "info": "#6b7684",
}


@dataclass
class ReportTheme:
    brand: str = "Infiltr"
    client: str = ""
    primary: str = "#3ddc97"
    accent: str = "#2bb3ff"
    logo: str = "◭"  # emoji/char or data: URI
    footer: str = "Generated by Infiltr — authorized testing only."


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _severity_counts(scan: dict[str, Any]) -> dict[str, int]:
    counts = {s: 0 for s in SEVERITY_ORDER}
    for r in scan.get("results", []):
        for f in r.get("findings", []):
            sev = f.get("severity", "info")
            if sev in counts:
                counts[sev] += 1
    return counts


def _sorted_results(scan: dict[str, Any]) -> list[dict]:
    return sorted(
        scan.get("results", []),
        key=lambda r: (-severity_rank(r.get("severity")), r.get("module", "")),
    )


# ---------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------
def render_markdown(scan: dict[str, Any], theme: ReportTheme | None = None) -> str:
    theme = theme or ReportTheme()
    counts = _severity_counts(scan)
    lines: list[str] = []
    lines.append(f"# {theme.brand} Security Scan Report")
    if theme.client:
        lines.append(f"**Client:** {theme.client}  ")
    lines.append(f"**Target:** `{scan['target']}`  ")
    lines.append(f"**Scan ID:** #{scan['id']}  ")
    lines.append(f"**Started:** {scan.get('started_at', '')}  ")
    lines.append(f"**Generated:** {_now()}  ")
    lines.append("")
    lines.append("## Severity summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in reversed(SEVERITY_ORDER):
        lines.append(f"| {sev.capitalize()} | {counts[sev]} |")
    lines.append(f"| **Total** | **{scan.get('finding_count', 0)}** |")
    lines.append("")
    lines.append(f"**Highest severity:** {scan.get('top_severity', 'info').upper()}")
    lines.append("")
    lines.append("## Modules")
    lines.append("")
    for r in _sorted_results(scan):
        lines.append(f"### {r['module']} ({r.get('category', '')})")
        lines.append("")
        lines.append(f"- **Status:** {r.get('status')}")
        lines.append(f"- **Severity:** {r.get('severity', 'info').upper()}")
        lines.append(f"- **Duration:** {r.get('duration', 0)}s")
        if r.get("command"):
            lines.append(f"- **Command:** `{r['command']}`")
        lines.append(f"- **Summary:** {r.get('summary', '')}")
        if r.get("error"):
            lines.append(f"- **Error:** {r['error']}")
        findings = r.get("findings", [])
        if findings:
            lines.append("")
            lines.append("| Severity | Type | Name | Value | Detail |")
            lines.append("|----------|------|------|-------|--------|")
            for f in findings:
                lines.append(
                    f"| {f.get('severity','info')} | {f.get('type','')} | "
                    f"{f.get('name','')} | {f.get('value','')} | {f.get('detail','')} |"
                )
        lines.append("")
    lines.append("---")
    lines.append(f"_{theme.footer}_")
    return "\n".join(lines)


# ---------------------------------------------------------------------
# HTML (self-contained)
# ---------------------------------------------------------------------
def _esc(s: Any) -> str:
    return _html.escape(str(s if s is not None else ""))


def render_html(scan: dict[str, Any], theme: ReportTheme | None = None) -> str:
    theme = theme or ReportTheme()
    counts = _severity_counts(scan)

    sev_cards = "".join(
        f"""<div class="sev-card" style="--c:{SEV_COLORS[s]}">
              <div class="sev-n">{counts[s]}</div>
              <div class="sev-l">{s.capitalize()}</div>
            </div>"""
        for s in reversed(SEVERITY_ORDER)
    )

    module_sections = []
    for r in _sorted_results(scan):
        rows = "".join(
            f"""<tr>
                  <td><span class="pill" style="--c:{SEV_COLORS.get(f.get('severity','info'),'#6b7684')}">{_esc(f.get('severity','info'))}</span></td>
                  <td class="mono">{_esc(f.get('type',''))}</td>
                  <td class="mono">{_esc(f.get('name',''))}</td>
                  <td class="mono">{_esc(f.get('value',''))}</td>
                  <td>{_esc(f.get('detail',''))}</td>
                </tr>"""
            for f in r.get("findings", [])
        )
        table = (
            f"""<table class="ftable"><thead><tr>
                  <th>Severity</th><th>Type</th><th>Name</th><th>Value</th><th>Detail</th>
                </tr></thead><tbody>{rows}</tbody></table>"""
            if r.get("findings") else '<p class="muted">No findings.</p>'
        )
        err = f'<div class="err">⚠ {_esc(r["error"])}</div>' if r.get("error") else ""
        module_sections.append(
            f"""<section class="module">
                  <div class="module-head">
                    <h3>{_esc(r['module'])} <span class="cat">{_esc(r.get('category',''))}</span></h3>
                    <span class="pill" style="--c:{SEV_COLORS.get(r.get('severity','info'),'#6b7684')}">{_esc(r.get('severity','info'))}</span>
                  </div>
                  <div class="meta">status <b>{_esc(r.get('status'))}</b> · {_esc(r.get('duration',0))}s · {_esc(r.get('summary',''))}</div>
                  {f'<div class="cmd mono">{_esc(r.get("command",""))}</div>' if r.get('command') else ''}
                  {err}
                  {table}
                </section>"""
        )

    client_line = f'<div class="sub">Client · {_esc(theme.client)}</div>' if theme.client else ""

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<title>{_esc(theme.brand)} Report — {_esc(scan['target'])}</title>
<style>
  :root {{ --primary:{theme.primary}; --accent:{theme.accent}; }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{ font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; color:#1a2230; background:#fff; line-height:1.5; }}
  .wrap {{ max-width:960px; margin:0 auto; padding:48px 40px; }}
  .cover {{ border-bottom:3px solid var(--primary); padding-bottom:28px; margin-bottom:32px; }}
  .logo {{ display:inline-grid; place-items:center; width:52px; height:52px; border-radius:12px;
           background:linear-gradient(135deg,var(--primary),var(--accent)); color:#04140d; font-size:30px; font-weight:700; }}
  h1 {{ font-size:30px; margin:16px 0 6px; }}
  .sub {{ color:#5a6674; font-size:14px; }}
  .kv {{ display:flex; flex-wrap:wrap; gap:8px 28px; margin-top:16px; font-size:14px; color:#374151; }}
  .kv b {{ color:#0b1220; }}
  .mono {{ font-family:"SF Mono",ui-monospace,Menlo,monospace; }}
  h2 {{ font-size:19px; margin:34px 0 14px; }}
  .sev-row {{ display:grid; grid-template-columns:repeat(5,1fr); gap:12px; }}
  .sev-card {{ border:1px solid #e5e9f0; border-top:4px solid var(--c); border-radius:10px; padding:16px; text-align:center; }}
  .sev-n {{ font-size:28px; font-weight:700; color:var(--c); }}
  .sev-l {{ font-size:12px; text-transform:uppercase; letter-spacing:1px; color:#6b7280; margin-top:4px; }}
  .module {{ border:1px solid #e5e9f0; border-radius:12px; padding:20px; margin-bottom:18px; }}
  .module-head {{ display:flex; align-items:center; justify-content:space-between; }}
  .module-head h3 {{ font-size:17px; font-family:"SF Mono",ui-monospace,Menlo,monospace; }}
  .cat {{ font-size:11px; color:#8b98a9; text-transform:uppercase; margin-left:6px; }}
  .meta {{ color:#5a6674; font-size:13px; margin:8px 0; }}
  .cmd {{ background:#0b1220; color:#9fe7c7; padding:8px 12px; border-radius:8px; font-size:12px; overflow-x:auto; margin:8px 0; }}
  .err {{ background:#fff4f4; color:#b3261e; border:1px solid #f3c0bd; padding:8px 12px; border-radius:8px; font-size:13px; margin:8px 0; }}
  .pill {{ display:inline-block; padding:2px 9px; border-radius:20px; font-size:11px; font-weight:700; text-transform:uppercase;
           color:var(--c); background:color-mix(in srgb,var(--c) 14%,transparent); border:1px solid color-mix(in srgb,var(--c) 40%,transparent); }}
  table.ftable {{ width:100%; border-collapse:collapse; margin-top:12px; font-size:13px; }}
  .ftable th {{ text-align:left; padding:8px 10px; background:#f6f8fb; border-bottom:1px solid #e5e9f0; font-size:11px; text-transform:uppercase; letter-spacing:.5px; color:#6b7280; }}
  .ftable td {{ padding:8px 10px; border-bottom:1px solid #eef1f6; vertical-align:top; word-break:break-word; }}
  .muted {{ color:#9aa4b2; font-size:13px; margin-top:8px; }}
  .footer {{ margin-top:40px; padding-top:18px; border-top:1px solid #e5e9f0; color:#8b98a9; font-size:12px; }}
</style></head>
<body><div class="wrap">
  <div class="cover">
    <div class="logo">{_esc(theme.logo)}</div>
    <h1>{_esc(theme.brand)} — Security Scan Report</h1>
    {client_line}
    <div class="kv">
      <span>Target <b class="mono">{_esc(scan['target'])}</b></span>
      <span>Scan <b>#{_esc(scan['id'])}</b></span>
      <span>Started <b>{_esc(scan.get('started_at',''))}</b></span>
      <span>Modules <b>{_esc(scan.get('module_count',0))}</b></span>
      <span>Findings <b>{_esc(scan.get('finding_count',0))}</b></span>
      <span>Highest <b>{_esc(scan.get('top_severity','info')).upper()}</b></span>
      <span>Generated <b>{_now()}</b></span>
    </div>
  </div>

  <h2>Severity summary</h2>
  <div class="sev-row">{sev_cards}</div>

  <h2>Module results</h2>
  {''.join(module_sections)}

  <div class="footer">{_esc(theme.footer)}</div>
</div></body></html>"""


# ---------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------
def render_pdf(scan: dict[str, Any], theme: ReportTheme | None = None) -> bytes:
    if not PDF_AVAILABLE:
        raise RuntimeError(
            "PDF generation requires WeasyPrint (pip install weasyprint + system libs). "
            "Use format=html or format=md instead."
        )
    html_str = render_html(scan, theme)
    return _WeasyHTML(string=html_str).write_pdf()
